#!/usr/bin/env ruby
# frozen_string_literal: true

require 'words'

if $PROGRAM_NAME == __FILE__
  if ARGV.empty?
    puts "Usage: #{$PROGRAM_NAME} DICTIONARY_FILE"
    exit 1
  end
  fourgrams = Words::FourGrams.new(File.read(ARGV[0]))
  File.open('sequences', 'w') do |sequences|
    sequences << fourgrams.sequences.join("\n")
  end
  File.open('words', 'w') do |words|
    words << fourgrams.words.join("\n")
  end
end
